language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="index"
   - PINS="index:."
 matrix:
   - DISTRO=alpine OCAML_VERSION=4.06
